# standard jekyll configuration

permalink: date
pygments: true
exclude: ['Rakefile', 'README.md', 'config.rb']
markdown: rdiscount

# configuration required for some pages

domain: example.com
title: Mackeracher
author: Anson MacKeracher
email: anson@mackeracher.com

# configuration for ehancements, uncomment to enable

# feedburner:
#   id: feedburnerid

# google_analytics:
#   account: UA-XXXXX-X

# github:
#   username: ghusername

# disqus:
#   id: disqusid
